name: lint

on:
  merge_group:
  pull_request:
    branches:
      - main

permissions:
  contents: none

jobs:
  conventional-commits:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0

      - name: Cache npm install
        id: cache-node-modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: node-modules-dev-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.json') }}
          path: |
            node_modules
      - name: Install debug NPM packages
        run: |
          npm install -D

      - name: Validate PR commits with commitlint
        id: cc
        env:
          COMMITLINT_START_REF: ${{ github.event.pull_request.base.sha || 'HEAD^' }}
          COMMITLINT_END_REF: ${{ github.event.pull_request.head.sha || 'HEAD' }}
        run: |
          node scripts/lint-cc.mjs

      - name: Create CC fix comment
        if: ${{ steps.cc.outputs.fail == 'true' }}
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT || secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: tip-cc
          recreate: true
          hide_and_recreate: true
          skip_unchanged: true
          message: | # markdown
            ### :warning: It looks like your commit is not formatted in line with Conventional Commits

            This repository uses [Conventional Commits][cc] to enable automation and ensure consistent commit messages across the project.

            ### ❌ Errors

            | Error Name | Error Message | Commit Message |
            |------------|---------------|----------------|
            ${{ steps.cc.outputs.error-rows-md-table }}

            ### ⚠ Warnings

            | Warning Name | Warning Message | Commit Message |
            |------------|---------------|----------------|
            ${{ steps.cc.outputs.warning-rows-md-table }}

            ### How to fix this issue

            Please `git amend` (including a `git rebase` if necessary) your commits to follow the [Conventional Commits][cc] format.

            > [!NOTE]
            > If you don't feel comfortable doing this, don't worry—a project maintainer can help correct this for you, before merging.
            >
            > Ensure that maintainers are allowed to modify your pull requests.

            [cc]: https://www.conventionalcommits.org/en/v1.0.0

      - name: Hide PR Comment
        if: ${{ steps.cc.outputs.success == 'true' }}
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT || secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: tip-cc
          hide: true
          hide_classify: "RESOLVED"
          append: true
          skip_unchanged: true
          only_update: true
          message: "This PR is now formatted in line with Conventional Commits"
